make:
	gcc -o info.cgi info.c
	gcc -o get_datta.cgi get_datta.c
	gcc -o get_telemetry.cgi get_telemetry.c
	gcc -o erase_datta.cgi erase_datta.c
	gcc -o modulos.cgi modulos.c
	gcc -o lista_modulos.cgi lista_modulos.c
	gcc -o simulador simulador.c
clean:
	rm --o info.cgi
	rm --o get_datta.cgi
	rm --o get_telemetry.cgi
	rm --o erase_datta.cgi
	rm --o modulos.cgi
	rm --o lista_modulos.cgi
	rm --o simulador

