Objeto: server.o simulador.o
	gcc -o server server.o
	gcc -o simulador simulador.o

Compilación : server.c simulador.o
	gcc -o server server.c simulador simulador.c

Limpieza :
	rm server server.o
	rm simulador simulador.o
